name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate animation
        uses: Platane/snk@master
        with:
          github_user_name: shalinikannan23
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg

      - name: Commit generated files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Add snake SVG"
