name: Generate Snake Animation

on:
  # ✅ Allows manual run from GitHub Actions tab
  workflow_dispatch:

  # ✅ Runs every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: shalinikannan23
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
