name: Generate Contribution Graph Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate SVG
        uses: Platane/snk@master
        with:
          github_user_name: shalinikannan23  # ← change to your GitHub username
          outputs: |
            dist/github-contribution-grid-pacman.svg
            dist/github-contribution-grid-pacman-dark.svg

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
